/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUserProfileRouteImport } from './routes/dashboard/user-profile'
import { Route as DashboardActivityLogRouteImport } from './routes/dashboard/activity-log'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashboardWalletIndexRouteImport } from './routes/dashboard/wallet/index'
import { Route as DashboardVerificationsIndexRouteImport } from './routes/dashboard/verifications/index'
import { Route as DashboardTransactionIndexRouteImport } from './routes/dashboard/transaction/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardReportIndexRouteImport } from './routes/dashboard/report/index'
import { Route as DashboardMnosIndexRouteImport } from './routes/dashboard/mnos/index'
import { Route as DashboardDisputeIndexRouteImport } from './routes/dashboard/dispute/index'
import { Route as DashboardCurrencyIndexRouteImport } from './routes/dashboard/currency/index'
import { Route as DashboardCreditCardIndexRouteImport } from './routes/dashboard/credit-card/index'
import { Route as DashboardBillPaymentIndexRouteImport } from './routes/dashboard/bill-payment/index'
import { Route as DashboardVerificationsIdRouteImport } from './routes/dashboard/verifications/$id'
import { Route as DashboardTransactionWithdrawalRouteImport } from './routes/dashboard/transaction/withdrawal'
import { Route as DashboardTransactionTransferRouteImport } from './routes/dashboard/transaction/transfer'
import { Route as DashboardTransactionRequestPaymentRouteImport } from './routes/dashboard/transaction/request-payment'
import { Route as DashboardTransactionExchangeRouteImport } from './routes/dashboard/transaction/exchange'
import { Route as DashboardTransactionDepositRouteImport } from './routes/dashboard/transaction/deposit'
import { Route as DashboardTransactionAllRouteImport } from './routes/dashboard/transaction/all'
import { Route as DashboardSettingsUserRoleRouteImport } from './routes/dashboard/settings/user-role'
import { Route as DashboardSettingsSystemRouteImport } from './routes/dashboard/settings/system'
import { Route as DashboardSettingsSecurityRouteImport } from './routes/dashboard/settings/security'
import { Route as DashboardSettingsNotificationsRouteImport } from './routes/dashboard/settings/notifications'
import { Route as DashboardSettingsCreateRoleRouteImport } from './routes/dashboard/settings/create-role'
import { Route as DashboardBillsBillerRouteImport } from './routes/dashboard/bills/biller'
import { Route as DashboardUserMarchantIndexRouteImport } from './routes/dashboard/user/marchant/index'
import { Route as DashboardUserListsIndexRouteImport } from './routes/dashboard/user/lists/index'
import { Route as DashboardUserAdminIndexRouteImport } from './routes/dashboard/user/admin/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserProfileRoute = DashboardUserProfileRouteImport.update({
  id: '/dashboard/user-profile',
  path: '/dashboard/user-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardActivityLogRoute = DashboardActivityLogRouteImport.update({
  id: '/dashboard/activity-log',
  path: '/dashboard/activity-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWalletIndexRoute = DashboardWalletIndexRouteImport.update({
  id: '/dashboard/wallet/',
  path: '/dashboard/wallet/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVerificationsIndexRoute =
  DashboardVerificationsIndexRouteImport.update({
    id: '/dashboard/verifications/',
    path: '/dashboard/verifications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTransactionIndexRoute =
  DashboardTransactionIndexRouteImport.update({
    id: '/dashboard/transaction/',
    path: '/dashboard/transaction/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/dashboard/settings/',
  path: '/dashboard/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportIndexRoute = DashboardReportIndexRouteImport.update({
  id: '/dashboard/report/',
  path: '/dashboard/report/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMnosIndexRoute = DashboardMnosIndexRouteImport.update({
  id: '/dashboard/mnos/',
  path: '/dashboard/mnos/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDisputeIndexRoute = DashboardDisputeIndexRouteImport.update({
  id: '/dashboard/dispute/',
  path: '/dashboard/dispute/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCurrencyIndexRoute = DashboardCurrencyIndexRouteImport.update({
  id: '/dashboard/currency/',
  path: '/dashboard/currency/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCreditCardIndexRoute =
  DashboardCreditCardIndexRouteImport.update({
    id: '/dashboard/credit-card/',
    path: '/dashboard/credit-card/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardBillPaymentIndexRoute =
  DashboardBillPaymentIndexRouteImport.update({
    id: '/dashboard/bill-payment/',
    path: '/dashboard/bill-payment/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardVerificationsIdRoute =
  DashboardVerificationsIdRouteImport.update({
    id: '/dashboard/verifications/$id',
    path: '/dashboard/verifications/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTransactionWithdrawalRoute =
  DashboardTransactionWithdrawalRouteImport.update({
    id: '/dashboard/transaction/withdrawal',
    path: '/dashboard/transaction/withdrawal',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTransactionTransferRoute =
  DashboardTransactionTransferRouteImport.update({
    id: '/dashboard/transaction/transfer',
    path: '/dashboard/transaction/transfer',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTransactionRequestPaymentRoute =
  DashboardTransactionRequestPaymentRouteImport.update({
    id: '/dashboard/transaction/request-payment',
    path: '/dashboard/transaction/request-payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTransactionExchangeRoute =
  DashboardTransactionExchangeRouteImport.update({
    id: '/dashboard/transaction/exchange',
    path: '/dashboard/transaction/exchange',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTransactionDepositRoute =
  DashboardTransactionDepositRouteImport.update({
    id: '/dashboard/transaction/deposit',
    path: '/dashboard/transaction/deposit',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTransactionAllRoute = DashboardTransactionAllRouteImport.update({
  id: '/dashboard/transaction/all',
  path: '/dashboard/transaction/all',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsUserRoleRoute =
  DashboardSettingsUserRoleRouteImport.update({
    id: '/dashboard/settings/user-role',
    path: '/dashboard/settings/user-role',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSettingsSystemRoute = DashboardSettingsSystemRouteImport.update({
  id: '/dashboard/settings/system',
  path: '/dashboard/settings/system',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsSecurityRoute =
  DashboardSettingsSecurityRouteImport.update({
    id: '/dashboard/settings/security',
    path: '/dashboard/settings/security',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSettingsNotificationsRoute =
  DashboardSettingsNotificationsRouteImport.update({
    id: '/dashboard/settings/notifications',
    path: '/dashboard/settings/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSettingsCreateRoleRoute =
  DashboardSettingsCreateRoleRouteImport.update({
    id: '/dashboard/settings/create-role',
    path: '/dashboard/settings/create-role',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardBillsBillerRoute = DashboardBillsBillerRouteImport.update({
  id: '/dashboard/bills/biller',
  path: '/dashboard/bills/biller',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserMarchantIndexRoute =
  DashboardUserMarchantIndexRouteImport.update({
    id: '/dashboard/user/marchant/',
    path: '/dashboard/user/marchant/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardUserListsIndexRoute = DashboardUserListsIndexRouteImport.update({
  id: '/dashboard/user/lists/',
  path: '/dashboard/user/lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserAdminIndexRoute = DashboardUserAdminIndexRouteImport.update({
  id: '/dashboard/user/admin/',
  path: '/dashboard/user/admin/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/activity-log': typeof DashboardActivityLogRoute
  '/dashboard/user-profile': typeof DashboardUserProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/bills/biller': typeof DashboardBillsBillerRoute
  '/dashboard/settings/create-role': typeof DashboardSettingsCreateRoleRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/system': typeof DashboardSettingsSystemRoute
  '/dashboard/settings/user-role': typeof DashboardSettingsUserRoleRoute
  '/dashboard/transaction/all': typeof DashboardTransactionAllRoute
  '/dashboard/transaction/deposit': typeof DashboardTransactionDepositRoute
  '/dashboard/transaction/exchange': typeof DashboardTransactionExchangeRoute
  '/dashboard/transaction/request-payment': typeof DashboardTransactionRequestPaymentRoute
  '/dashboard/transaction/transfer': typeof DashboardTransactionTransferRoute
  '/dashboard/transaction/withdrawal': typeof DashboardTransactionWithdrawalRoute
  '/dashboard/verifications/$id': typeof DashboardVerificationsIdRoute
  '/dashboard/bill-payment/': typeof DashboardBillPaymentIndexRoute
  '/dashboard/credit-card/': typeof DashboardCreditCardIndexRoute
  '/dashboard/currency/': typeof DashboardCurrencyIndexRoute
  '/dashboard/dispute/': typeof DashboardDisputeIndexRoute
  '/dashboard/mnos/': typeof DashboardMnosIndexRoute
  '/dashboard/report/': typeof DashboardReportIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/transaction/': typeof DashboardTransactionIndexRoute
  '/dashboard/verifications/': typeof DashboardVerificationsIndexRoute
  '/dashboard/wallet/': typeof DashboardWalletIndexRoute
  '/dashboard/user/admin/': typeof DashboardUserAdminIndexRoute
  '/dashboard/user/lists/': typeof DashboardUserListsIndexRoute
  '/dashboard/user/marchant/': typeof DashboardUserMarchantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/activity-log': typeof DashboardActivityLogRoute
  '/dashboard/user-profile': typeof DashboardUserProfileRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/bills/biller': typeof DashboardBillsBillerRoute
  '/dashboard/settings/create-role': typeof DashboardSettingsCreateRoleRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/system': typeof DashboardSettingsSystemRoute
  '/dashboard/settings/user-role': typeof DashboardSettingsUserRoleRoute
  '/dashboard/transaction/all': typeof DashboardTransactionAllRoute
  '/dashboard/transaction/deposit': typeof DashboardTransactionDepositRoute
  '/dashboard/transaction/exchange': typeof DashboardTransactionExchangeRoute
  '/dashboard/transaction/request-payment': typeof DashboardTransactionRequestPaymentRoute
  '/dashboard/transaction/transfer': typeof DashboardTransactionTransferRoute
  '/dashboard/transaction/withdrawal': typeof DashboardTransactionWithdrawalRoute
  '/dashboard/verifications/$id': typeof DashboardVerificationsIdRoute
  '/dashboard/bill-payment': typeof DashboardBillPaymentIndexRoute
  '/dashboard/credit-card': typeof DashboardCreditCardIndexRoute
  '/dashboard/currency': typeof DashboardCurrencyIndexRoute
  '/dashboard/dispute': typeof DashboardDisputeIndexRoute
  '/dashboard/mnos': typeof DashboardMnosIndexRoute
  '/dashboard/report': typeof DashboardReportIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/transaction': typeof DashboardTransactionIndexRoute
  '/dashboard/verifications': typeof DashboardVerificationsIndexRoute
  '/dashboard/wallet': typeof DashboardWalletIndexRoute
  '/dashboard/user/admin': typeof DashboardUserAdminIndexRoute
  '/dashboard/user/lists': typeof DashboardUserListsIndexRoute
  '/dashboard/user/marchant': typeof DashboardUserMarchantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/activity-log': typeof DashboardActivityLogRoute
  '/dashboard/user-profile': typeof DashboardUserProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/bills/biller': typeof DashboardBillsBillerRoute
  '/dashboard/settings/create-role': typeof DashboardSettingsCreateRoleRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/system': typeof DashboardSettingsSystemRoute
  '/dashboard/settings/user-role': typeof DashboardSettingsUserRoleRoute
  '/dashboard/transaction/all': typeof DashboardTransactionAllRoute
  '/dashboard/transaction/deposit': typeof DashboardTransactionDepositRoute
  '/dashboard/transaction/exchange': typeof DashboardTransactionExchangeRoute
  '/dashboard/transaction/request-payment': typeof DashboardTransactionRequestPaymentRoute
  '/dashboard/transaction/transfer': typeof DashboardTransactionTransferRoute
  '/dashboard/transaction/withdrawal': typeof DashboardTransactionWithdrawalRoute
  '/dashboard/verifications/$id': typeof DashboardVerificationsIdRoute
  '/dashboard/bill-payment/': typeof DashboardBillPaymentIndexRoute
  '/dashboard/credit-card/': typeof DashboardCreditCardIndexRoute
  '/dashboard/currency/': typeof DashboardCurrencyIndexRoute
  '/dashboard/dispute/': typeof DashboardDisputeIndexRoute
  '/dashboard/mnos/': typeof DashboardMnosIndexRoute
  '/dashboard/report/': typeof DashboardReportIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/transaction/': typeof DashboardTransactionIndexRoute
  '/dashboard/verifications/': typeof DashboardVerificationsIndexRoute
  '/dashboard/wallet/': typeof DashboardWalletIndexRoute
  '/dashboard/user/admin/': typeof DashboardUserAdminIndexRoute
  '/dashboard/user/lists/': typeof DashboardUserListsIndexRoute
  '/dashboard/user/marchant/': typeof DashboardUserMarchantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/dashboard/activity-log'
    | '/dashboard/user-profile'
    | '/dashboard/'
    | '/dashboard/bills/biller'
    | '/dashboard/settings/create-role'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/security'
    | '/dashboard/settings/system'
    | '/dashboard/settings/user-role'
    | '/dashboard/transaction/all'
    | '/dashboard/transaction/deposit'
    | '/dashboard/transaction/exchange'
    | '/dashboard/transaction/request-payment'
    | '/dashboard/transaction/transfer'
    | '/dashboard/transaction/withdrawal'
    | '/dashboard/verifications/$id'
    | '/dashboard/bill-payment/'
    | '/dashboard/credit-card/'
    | '/dashboard/currency/'
    | '/dashboard/dispute/'
    | '/dashboard/mnos/'
    | '/dashboard/report/'
    | '/dashboard/settings/'
    | '/dashboard/transaction/'
    | '/dashboard/verifications/'
    | '/dashboard/wallet/'
    | '/dashboard/user/admin/'
    | '/dashboard/user/lists/'
    | '/dashboard/user/marchant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/dashboard/activity-log'
    | '/dashboard/user-profile'
    | '/dashboard'
    | '/dashboard/bills/biller'
    | '/dashboard/settings/create-role'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/security'
    | '/dashboard/settings/system'
    | '/dashboard/settings/user-role'
    | '/dashboard/transaction/all'
    | '/dashboard/transaction/deposit'
    | '/dashboard/transaction/exchange'
    | '/dashboard/transaction/request-payment'
    | '/dashboard/transaction/transfer'
    | '/dashboard/transaction/withdrawal'
    | '/dashboard/verifications/$id'
    | '/dashboard/bill-payment'
    | '/dashboard/credit-card'
    | '/dashboard/currency'
    | '/dashboard/dispute'
    | '/dashboard/mnos'
    | '/dashboard/report'
    | '/dashboard/settings'
    | '/dashboard/transaction'
    | '/dashboard/verifications'
    | '/dashboard/wallet'
    | '/dashboard/user/admin'
    | '/dashboard/user/lists'
    | '/dashboard/user/marchant'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/dashboard/activity-log'
    | '/dashboard/user-profile'
    | '/dashboard/'
    | '/dashboard/bills/biller'
    | '/dashboard/settings/create-role'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/security'
    | '/dashboard/settings/system'
    | '/dashboard/settings/user-role'
    | '/dashboard/transaction/all'
    | '/dashboard/transaction/deposit'
    | '/dashboard/transaction/exchange'
    | '/dashboard/transaction/request-payment'
    | '/dashboard/transaction/transfer'
    | '/dashboard/transaction/withdrawal'
    | '/dashboard/verifications/$id'
    | '/dashboard/bill-payment/'
    | '/dashboard/credit-card/'
    | '/dashboard/currency/'
    | '/dashboard/dispute/'
    | '/dashboard/mnos/'
    | '/dashboard/report/'
    | '/dashboard/settings/'
    | '/dashboard/transaction/'
    | '/dashboard/verifications/'
    | '/dashboard/wallet/'
    | '/dashboard/user/admin/'
    | '/dashboard/user/lists/'
    | '/dashboard/user/marchant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  DashboardActivityLogRoute: typeof DashboardActivityLogRoute
  DashboardUserProfileRoute: typeof DashboardUserProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBillsBillerRoute: typeof DashboardBillsBillerRoute
  DashboardSettingsCreateRoleRoute: typeof DashboardSettingsCreateRoleRoute
  DashboardSettingsNotificationsRoute: typeof DashboardSettingsNotificationsRoute
  DashboardSettingsSecurityRoute: typeof DashboardSettingsSecurityRoute
  DashboardSettingsSystemRoute: typeof DashboardSettingsSystemRoute
  DashboardSettingsUserRoleRoute: typeof DashboardSettingsUserRoleRoute
  DashboardTransactionAllRoute: typeof DashboardTransactionAllRoute
  DashboardTransactionDepositRoute: typeof DashboardTransactionDepositRoute
  DashboardTransactionExchangeRoute: typeof DashboardTransactionExchangeRoute
  DashboardTransactionRequestPaymentRoute: typeof DashboardTransactionRequestPaymentRoute
  DashboardTransactionTransferRoute: typeof DashboardTransactionTransferRoute
  DashboardTransactionWithdrawalRoute: typeof DashboardTransactionWithdrawalRoute
  DashboardVerificationsIdRoute: typeof DashboardVerificationsIdRoute
  DashboardBillPaymentIndexRoute: typeof DashboardBillPaymentIndexRoute
  DashboardCreditCardIndexRoute: typeof DashboardCreditCardIndexRoute
  DashboardCurrencyIndexRoute: typeof DashboardCurrencyIndexRoute
  DashboardDisputeIndexRoute: typeof DashboardDisputeIndexRoute
  DashboardMnosIndexRoute: typeof DashboardMnosIndexRoute
  DashboardReportIndexRoute: typeof DashboardReportIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardTransactionIndexRoute: typeof DashboardTransactionIndexRoute
  DashboardVerificationsIndexRoute: typeof DashboardVerificationsIndexRoute
  DashboardWalletIndexRoute: typeof DashboardWalletIndexRoute
  DashboardUserAdminIndexRoute: typeof DashboardUserAdminIndexRoute
  DashboardUserListsIndexRoute: typeof DashboardUserListsIndexRoute
  DashboardUserMarchantIndexRoute: typeof DashboardUserMarchantIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/user-profile': {
      id: '/dashboard/user-profile'
      path: '/dashboard/user-profile'
      fullPath: '/dashboard/user-profile'
      preLoaderRoute: typeof DashboardUserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/activity-log': {
      id: '/dashboard/activity-log'
      path: '/dashboard/activity-log'
      fullPath: '/dashboard/activity-log'
      preLoaderRoute: typeof DashboardActivityLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wallet/': {
      id: '/dashboard/wallet/'
      path: '/dashboard/wallet'
      fullPath: '/dashboard/wallet/'
      preLoaderRoute: typeof DashboardWalletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/verifications/': {
      id: '/dashboard/verifications/'
      path: '/dashboard/verifications'
      fullPath: '/dashboard/verifications/'
      preLoaderRoute: typeof DashboardVerificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transaction/': {
      id: '/dashboard/transaction/'
      path: '/dashboard/transaction'
      fullPath: '/dashboard/transaction/'
      preLoaderRoute: typeof DashboardTransactionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/report/': {
      id: '/dashboard/report/'
      path: '/dashboard/report'
      fullPath: '/dashboard/report/'
      preLoaderRoute: typeof DashboardReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/mnos/': {
      id: '/dashboard/mnos/'
      path: '/dashboard/mnos'
      fullPath: '/dashboard/mnos/'
      preLoaderRoute: typeof DashboardMnosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/dispute/': {
      id: '/dashboard/dispute/'
      path: '/dashboard/dispute'
      fullPath: '/dashboard/dispute/'
      preLoaderRoute: typeof DashboardDisputeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/currency/': {
      id: '/dashboard/currency/'
      path: '/dashboard/currency'
      fullPath: '/dashboard/currency/'
      preLoaderRoute: typeof DashboardCurrencyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/credit-card/': {
      id: '/dashboard/credit-card/'
      path: '/dashboard/credit-card'
      fullPath: '/dashboard/credit-card/'
      preLoaderRoute: typeof DashboardCreditCardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/bill-payment/': {
      id: '/dashboard/bill-payment/'
      path: '/dashboard/bill-payment'
      fullPath: '/dashboard/bill-payment/'
      preLoaderRoute: typeof DashboardBillPaymentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/verifications/$id': {
      id: '/dashboard/verifications/$id'
      path: '/dashboard/verifications/$id'
      fullPath: '/dashboard/verifications/$id'
      preLoaderRoute: typeof DashboardVerificationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transaction/withdrawal': {
      id: '/dashboard/transaction/withdrawal'
      path: '/dashboard/transaction/withdrawal'
      fullPath: '/dashboard/transaction/withdrawal'
      preLoaderRoute: typeof DashboardTransactionWithdrawalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transaction/transfer': {
      id: '/dashboard/transaction/transfer'
      path: '/dashboard/transaction/transfer'
      fullPath: '/dashboard/transaction/transfer'
      preLoaderRoute: typeof DashboardTransactionTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transaction/request-payment': {
      id: '/dashboard/transaction/request-payment'
      path: '/dashboard/transaction/request-payment'
      fullPath: '/dashboard/transaction/request-payment'
      preLoaderRoute: typeof DashboardTransactionRequestPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transaction/exchange': {
      id: '/dashboard/transaction/exchange'
      path: '/dashboard/transaction/exchange'
      fullPath: '/dashboard/transaction/exchange'
      preLoaderRoute: typeof DashboardTransactionExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transaction/deposit': {
      id: '/dashboard/transaction/deposit'
      path: '/dashboard/transaction/deposit'
      fullPath: '/dashboard/transaction/deposit'
      preLoaderRoute: typeof DashboardTransactionDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transaction/all': {
      id: '/dashboard/transaction/all'
      path: '/dashboard/transaction/all'
      fullPath: '/dashboard/transaction/all'
      preLoaderRoute: typeof DashboardTransactionAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/user-role': {
      id: '/dashboard/settings/user-role'
      path: '/dashboard/settings/user-role'
      fullPath: '/dashboard/settings/user-role'
      preLoaderRoute: typeof DashboardSettingsUserRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/system': {
      id: '/dashboard/settings/system'
      path: '/dashboard/settings/system'
      fullPath: '/dashboard/settings/system'
      preLoaderRoute: typeof DashboardSettingsSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/security': {
      id: '/dashboard/settings/security'
      path: '/dashboard/settings/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof DashboardSettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/notifications': {
      id: '/dashboard/settings/notifications'
      path: '/dashboard/settings/notifications'
      fullPath: '/dashboard/settings/notifications'
      preLoaderRoute: typeof DashboardSettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/create-role': {
      id: '/dashboard/settings/create-role'
      path: '/dashboard/settings/create-role'
      fullPath: '/dashboard/settings/create-role'
      preLoaderRoute: typeof DashboardSettingsCreateRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/bills/biller': {
      id: '/dashboard/bills/biller'
      path: '/dashboard/bills/biller'
      fullPath: '/dashboard/bills/biller'
      preLoaderRoute: typeof DashboardBillsBillerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/user/marchant/': {
      id: '/dashboard/user/marchant/'
      path: '/dashboard/user/marchant'
      fullPath: '/dashboard/user/marchant/'
      preLoaderRoute: typeof DashboardUserMarchantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/user/lists/': {
      id: '/dashboard/user/lists/'
      path: '/dashboard/user/lists'
      fullPath: '/dashboard/user/lists/'
      preLoaderRoute: typeof DashboardUserListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/user/admin/': {
      id: '/dashboard/user/admin/'
      path: '/dashboard/user/admin'
      fullPath: '/dashboard/user/admin/'
      preLoaderRoute: typeof DashboardUserAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  DashboardActivityLogRoute: DashboardActivityLogRoute,
  DashboardUserProfileRoute: DashboardUserProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBillsBillerRoute: DashboardBillsBillerRoute,
  DashboardSettingsCreateRoleRoute: DashboardSettingsCreateRoleRoute,
  DashboardSettingsNotificationsRoute: DashboardSettingsNotificationsRoute,
  DashboardSettingsSecurityRoute: DashboardSettingsSecurityRoute,
  DashboardSettingsSystemRoute: DashboardSettingsSystemRoute,
  DashboardSettingsUserRoleRoute: DashboardSettingsUserRoleRoute,
  DashboardTransactionAllRoute: DashboardTransactionAllRoute,
  DashboardTransactionDepositRoute: DashboardTransactionDepositRoute,
  DashboardTransactionExchangeRoute: DashboardTransactionExchangeRoute,
  DashboardTransactionRequestPaymentRoute:
    DashboardTransactionRequestPaymentRoute,
  DashboardTransactionTransferRoute: DashboardTransactionTransferRoute,
  DashboardTransactionWithdrawalRoute: DashboardTransactionWithdrawalRoute,
  DashboardVerificationsIdRoute: DashboardVerificationsIdRoute,
  DashboardBillPaymentIndexRoute: DashboardBillPaymentIndexRoute,
  DashboardCreditCardIndexRoute: DashboardCreditCardIndexRoute,
  DashboardCurrencyIndexRoute: DashboardCurrencyIndexRoute,
  DashboardDisputeIndexRoute: DashboardDisputeIndexRoute,
  DashboardMnosIndexRoute: DashboardMnosIndexRoute,
  DashboardReportIndexRoute: DashboardReportIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardTransactionIndexRoute: DashboardTransactionIndexRoute,
  DashboardVerificationsIndexRoute: DashboardVerificationsIndexRoute,
  DashboardWalletIndexRoute: DashboardWalletIndexRoute,
  DashboardUserAdminIndexRoute: DashboardUserAdminIndexRoute,
  DashboardUserListsIndexRoute: DashboardUserListsIndexRoute,
  DashboardUserMarchantIndexRoute: DashboardUserMarchantIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
