export const countries = [
  { code: 'US', name: 'United States', flag: '🇺🇸', prefix: '+1' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', prefix: '+1' },

  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', prefix: '+44' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', prefix: '+49' },
  { code: 'FR', name: 'France', flag: '🇫🇷', prefix: '+33' },

  { code: 'IN', name: 'India', flag: '🇮🇳', prefix: '+91' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵', prefix: '+81' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺', prefix: '+61' },

  { code: 'BR', name: 'Brazil', flag: '🇧🇷', prefix: '+55' },

  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', prefix: '+234' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', prefix: '+233' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', prefix: '+254' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦', prefix: '+27' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬', prefix: '+256' },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', prefix: '+255' },
  { code: 'ZM', name: 'Zambia', flag: '🇿🇲', prefix: '+260' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼', prefix: '+265' },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳', prefix: '+221' },
  { code: 'CI', name: "Côte d'Ivoire", flag: '🇨🇮', prefix: '+225' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱', prefix: '+223' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪', prefix: '+227' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬', prefix: '+228' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', prefix: '+226' },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯', prefix: '+229' },
  { code: 'GN', name: 'Guinea', flag: '🇬🇳', prefix: '+224' },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲', prefix: '+237' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦', prefix: '+241' },
  { code: 'CG', name: 'Republic of the Congo', flag: '🇨🇬', prefix: '+242' },
  { code: 'CD', name: 'Democratic Republic of the Congo', flag: '🇨🇩', prefix: '+243' },
  { code: 'CF', name: 'Central African Republic', flag: '🇨🇫', prefix: '+236' },
  { code: 'TD', name: 'Chad', flag: '🇹🇩', prefix: '+235' },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦', prefix: '+212' },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿', prefix: '+213' },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳', prefix: '+216' },
  { code: 'MR', name: 'Mauritania', flag: '🇲🇷', prefix: '+222' },
];
