export interface Permission {
  id: string;
  name: string;
  checked: boolean;
}

export const PERMISSIONS: Permission[] = [
  { id: 'dashboard', name: 'Dashboard', checked: false },
  { id: 'analytics', name: 'Analytics', checked: false },
  { id: 'users', name: 'Users', checked: false },
  { id: 'transactions', name: 'Transactions', checked: false },
  { id: 'wallets', name: 'Wallets', checked: false },
  { id: 'currency', name: 'Currency', checked: false },
  { id: 'reports', name: 'Reports', checked: false },
  { id: 'settings', name: 'Settings', checked: false },
  { id: 'support-tickets', name: 'Support Tickets', checked: false },
  { id: 'kyc-verification', name: 'KYC Verification', checked: false },
  { id: 'bill-payments', name: 'Bill Payments', checked: false },
  { id: 'credit-cards', name: 'Credit Cards', checked: false },
  { id: 'disputes', name: 'Disputes', checked: false },
  { id: 'mnos', name: 'MNOs', checked: false },
  { id: 'activity-logs', name: 'Activity Logs', checked: false },
  { id: 'user-management', name: 'User Management', checked: false },
  { id: 'role-management', name: 'Role Management', checked: false },
  { id: 'system-config', name: 'System Configuration', checked: false },
  { id: 'audit-trails', name: 'Audit Trails', checked: false },
  { id: 'notifications', name: 'Notifications', checked: false },
  { id: 'api-access', name: 'API Access', checked: false },
  { id: 'data-export', name: 'Data Export', checked: false },
  { id: 'backup-restore', name: 'Backup & Restore', checked: false },
  { id: 'security-settings', name: 'Security Settings', checked: false },
  { id: 'compliance', name: 'Compliance', checked: false },
  { id: 'merchant-management', name: 'Merchant Management', checked: false },
  { id: 'payment-processing', name: 'Payment Processing', checked: false },
  { id: 'fraud-detection', name: 'Fraud Detection', checked: false },
  { id: 'risk-management', name: 'Risk Management', checked: false },
  { id: 'customer-support', name: 'Customer Support', checked: false },
  { id: 'marketing-tools', name: 'Marketing Tools', checked: false },
  { id: 'integration-management', name: 'Integration Management', checked: false },
  { id: 'webhook-management', name: 'Webhook Management', checked: false },
  { id: 'rate-limiting', name: 'Rate Limiting', checked: false },
  { id: 'monitoring', name: 'Monitoring', checked: false },
  { id: 'performance-metrics', name: 'Performance Metrics', checked: false },
  { id: 'error-tracking', name: 'Error Tracking', checked: false },
  { id: 'log-management', name: 'Log Management', checked: false },
  { id: 'database-management', name: 'Database Management', checked: false },
  { id: 'server-management', name: 'Server Management', checked: false },
  { id: 'deployment', name: 'Deployment', checked: false },
  { id: 'version-control', name: 'Version Control', checked: false },
  { id: 'testing', name: 'Testing', checked: false },
  { id: 'documentation', name: 'Documentation', checked: false },
  { id: 'training', name: 'Training', checked: false },
  { id: 'onboarding', name: 'Onboarding', checked: false },
  { id: 'offboarding', name: 'Offboarding', checked: false },
  { id: 'policy-management', name: 'Policy Management', checked: false },
  { id: 'incident-response', name: 'Incident Response', checked: false },
  { id: 'disaster-recovery', name: 'Disaster Recovery', checked: false },
  { id: 'business-continuity', name: 'Business Continuity', checked: false },
  { id: 'vendor-management', name: 'Vendor Management', checked: false },
  { id: 'contract-management', name: 'Contract Management', checked: false },
  { id: 'budget-management', name: 'Budget Management', checked: false },
  { id: 'financial-reporting', name: 'Financial Reporting', checked: false },
  { id: 'tax-management', name: 'Tax Management', checked: false },
  { id: 'regulatory-compliance', name: 'Regulatory Compliance', checked: false },
  { id: 'data-privacy', name: 'Data Privacy', checked: false },
  { id: 'gdpr-compliance', name: 'GDPR Compliance', checked: false },
  { id: 'pci-compliance', name: 'PCI Compliance', checked: false },
  { id: 'sox-compliance', name: 'SOX Compliance', checked: false },
  { id: 'iso-compliance', name: 'ISO Compliance', checked: false },
  { id: 'security-audits', name: 'Security Audits', checked: false },
  { id: 'penetration-testing', name: 'Penetration Testing', checked: false },
  { id: 'vulnerability-assessment', name: 'Vulnerability Assessment', checked: false },
  { id: 'threat-intelligence', name: 'Threat Intelligence', checked: false },
  { id: 'incident-management', name: 'Incident Management', checked: false },
  { id: 'change-management', name: 'Change Management', checked: false },
  { id: 'release-management', name: 'Release Management', checked: false },
  { id: 'capacity-planning', name: 'Capacity Planning', checked: false },
  { id: 'resource-allocation', name: 'Resource Allocation', checked: false },
  { id: 'project-management', name: 'Project Management', checked: false },
  { id: 'task-management', name: 'Task Management', checked: false },
  { id: 'time-tracking', name: 'Time Tracking', checked: false },
  { id: 'expense-management', name: 'Expense Management', checked: false },
  { id: 'invoice-management', name: 'Invoice Management', checked: false },
  { id: 'procurement', name: 'Procurement', checked: false },
  { id: 'asset-management', name: 'Asset Management', checked: false },
  { id: 'inventory-management', name: 'Inventory Management', checked: false },
  { id: 'supply-chain', name: 'Supply Chain', checked: false },
  { id: 'logistics', name: 'Logistics', checked: false },
  { id: 'shipping', name: 'Shipping', checked: false },
  { id: 'delivery-tracking', name: 'Delivery Tracking', checked: false },
  { id: 'customer-feedback', name: 'Customer Feedback', checked: false },
  { id: 'survey-management', name: 'Survey Management', checked: false },
  { id: 'review-management', name: 'Review Management', checked: false },
  { id: 'social-media', name: 'Social Media', checked: false },
  { id: 'content-management', name: 'Content Management', checked: false },
  { id: 'seo-management', name: 'SEO Management', checked: false },
  { id: 'email-marketing', name: 'Email Marketing', checked: false },
  { id: 'campaign-management', name: 'Campaign Management', checked: false },
  { id: 'lead-generation', name: 'Lead Generation', checked: false },
  { id: 'crm', name: 'CRM', checked: false },
  { id: 'sales-management', name: 'Sales Management', checked: false },
  { id: 'pipeline-management', name: 'Pipeline Management', checked: false },
  { id: 'forecasting', name: 'Forecasting', checked: false },
  { id: 'territory-management', name: 'Territory Management', checked: false },
  { id: 'commission-management', name: 'Commission Management', checked: false },
  { id: 'partner-management', name: 'Partner Management', checked: false },
  { id: 'affiliate-management', name: 'Affiliate Management', checked: false },
  { id: 'referral-management', name: 'Referral Management', checked: false },
  { id: 'loyalty-programs', name: 'Loyalty Programs', checked: false },
  { id: 'rewards-management', name: 'Rewards Management', checked: false },
  { id: 'gamification', name: 'Gamification', checked: false },
  { id: 'personalization', name: 'Personalization', checked: false },
  { id: 'recommendation-engine', name: 'Recommendation Engine', checked: false },
  { id: 'ai-ml', name: 'AI/ML', checked: false },
  { id: 'data-science', name: 'Data Science', checked: false },
  { id: 'business-intelligence', name: 'Business Intelligence', checked: false },
  { id: 'data-visualization', name: 'Data Visualization', checked: false },
  { id: 'dashboard-creation', name: 'Dashboard Creation', checked: false },
  { id: 'report-generation', name: 'Report Generation', checked: false },
  { id: 'data-mining', name: 'Data Mining', checked: false },
  { id: 'predictive-analytics', name: 'Predictive Analytics', checked: false },
  { id: 'statistical-analysis', name: 'Statistical Analysis', checked: false },
  { id: 'a-b-testing', name: 'A/B Testing', checked: false },
  { id: 'multivariate-testing', name: 'Multivariate Testing', checked: false },
  { id: 'conversion-optimization', name: 'Conversion Optimization', checked: false },
  { id: 'user-experience', name: 'User Experience', checked: false },
  { id: 'user-interface', name: 'User Interface', checked: false },
  { id: 'design-system', name: 'Design System', checked: false },
  { id: 'brand-management', name: 'Brand Management', checked: false },
  { id: 'style-guide', name: 'Style Guide', checked: false },
  { id: 'accessibility', name: 'Accessibility', checked: false },
  { id: 'internationalization', name: 'Internationalization', checked: false },
  { id: 'localization', name: 'Localization', checked: false },
  { id: 'multi-language', name: 'Multi-language', checked: false },
  { id: 'multi-currency', name: 'Multi-currency', checked: false },
  { id: 'multi-timezone', name: 'Multi-timezone', checked: false },
  { id: 'geo-location', name: 'Geo-location', checked: false },
  { id: 'mapping', name: 'Mapping', checked: false },
  { id: 'gps-tracking', name: 'GPS Tracking', checked: false },
  { id: 'location-services', name: 'Location Services', checked: false },
  { id: 'mobile-app', name: 'Mobile App', checked: false },
  { id: 'web-app', name: 'Web App', checked: false },
  { id: 'desktop-app', name: 'Desktop App', checked: false },
  { id: 'api-development', name: 'API Development', checked: false },
  { id: 'microservices', name: 'Microservices', checked: false },
  { id: 'serverless', name: 'Serverless', checked: false },
  { id: 'cloud-computing', name: 'Cloud Computing', checked: false },
  { id: 'devops', name: 'DevOps', checked: false },
  { id: 'ci-cd', name: 'CI/CD', checked: false },
  { id: 'containerization', name: 'Containerization', checked: false },
  { id: 'orchestration', name: 'Orchestration', checked: false },
  { id: 'load-balancing', name: 'Load Balancing', checked: false },
  { id: 'auto-scaling', name: 'Auto Scaling', checked: false },
  { id: 'caching', name: 'Caching', checked: false },
  { id: 'cdn', name: 'CDN', checked: false },
  { id: 'edge-computing', name: 'Edge Computing', checked: false },
  { id: 'iot', name: 'IoT', checked: false },
  { id: 'blockchain', name: 'Blockchain', checked: false },
  { id: 'cryptocurrency', name: 'Cryptocurrency', checked: false },
  { id: 'smart-contracts', name: 'Smart Contracts', checked: false },
  { id: 'defi', name: 'DeFi', checked: false },
  { id: 'nft', name: 'NFT', checked: false },
  { id: 'web3', name: 'Web3', checked: false },
  { id: 'metaverse', name: 'Metaverse', checked: false },
  { id: 'ar-vr', name: 'AR/VR', checked: false },
  { id: 'quantum-computing', name: 'Quantum Computing', checked: false },
  { id: 'edge-ai', name: 'Edge AI', checked: false },
  { id: 'federated-learning', name: 'Federated Learning', checked: false },
  { id: 'neural-networks', name: 'Neural Networks', checked: false },
  { id: 'deep-learning', name: 'Deep Learning', checked: false },
  { id: 'computer-vision', name: 'Computer Vision', checked: false },
  { id: 'natural-language-processing', name: 'Natural Language Processing', checked: false },
  { id: 'speech-recognition', name: 'Speech Recognition', checked: false },
  { id: 'text-to-speech', name: 'Text-to-Speech', checked: false },
  { id: 'chatbots', name: 'Chatbots', checked: false },
  { id: 'virtual-assistants', name: 'Virtual Assistants', checked: false },
  { id: 'automation', name: 'Automation', checked: false },
  { id: 'workflow-automation', name: 'Workflow Automation', checked: false },
  { id: 'process-automation', name: 'Process Automation', checked: false },
  { id: 'robotic-process-automation', name: 'Robotic Process Automation', checked: false },
  { id: 'intelligent-automation', name: 'Intelligent Automation', checked: false },
  { id: 'hyperautomation', name: 'Hyperautomation', checked: false },
  { id: 'low-code', name: 'Low Code', checked: false },
  { id: 'no-code', name: 'No Code', checked: false },
  { id: 'citizen-development', name: 'Citizen Development', checked: false },
  { id: 'digital-transformation', name: 'Digital Transformation', checked: false },
  { id: 'innovation-management', name: 'Innovation Management', checked: false },
  { id: 'research-development', name: 'Research & Development', checked: false },
  { id: 'intellectual-property', name: 'Intellectual Property', checked: false },
  { id: 'patent-management', name: 'Patent Management', checked: false },
  { id: 'trademark-management', name: 'Trademark Management', checked: false },
  { id: 'copyright-management', name: 'Copyright Management', checked: false },
  { id: 'licensing', name: 'Licensing', checked: false },
  { id: 'open-source', name: 'Open Source', checked: false },
  { id: 'community-management', name: 'Community Management', checked: false },
  { id: 'developer-relations', name: 'Developer Relations', checked: false },
  { id: 'technical-writing', name: 'Technical Writing', checked: false },
  { id: 'knowledge-management', name: 'Knowledge Management', checked: false },
  { id: 'learning-management', name: 'Learning Management', checked: false },
  { id: 'e-learning', name: 'E-learning', checked: false },
  { id: 'certification', name: 'Certification', checked: false },
  { id: 'skill-assessment', name: 'Skill Assessment', checked: false },
  { id: 'performance-evaluation', name: 'Performance Evaluation', checked: false },
  { id: 'goal-setting', name: 'Goal Setting', checked: false },
  { id: 'okr-management', name: 'OKR Management', checked: false },
  { id: 'kpi-tracking', name: 'KPI Tracking', checked: false },
  { id: 'balanced-scorecard', name: 'Balanced Scorecard', checked: false },
  { id: 'strategic-planning', name: 'Strategic Planning', checked: false },
  { id: 'business-planning', name: 'Business Planning', checked: false },
  { id: 'market-research', name: 'Market Research', checked: false },
  { id: 'competitive-analysis', name: 'Competitive Analysis', checked: false },
  { id: 'swot-analysis', name: 'SWOT Analysis', checked: false },
  { id: 'pestle-analysis', name: 'PESTLE Analysis', checked: false },
  { id: 'porter-five-forces', name: 'Porter Five Forces', checked: false },
  { id: 'value-chain-analysis', name: 'Value Chain Analysis', checked: false },
  { id: 'business-model-canvas', name: 'Business Model Canvas', checked: false },
  { id: 'lean-canvas', name: 'Lean Canvas', checked: false },
  { id: 'design-thinking', name: 'Design Thinking', checked: false },
  { id: 'agile-methodology', name: 'Agile Methodology', checked: false },
  { id: 'scrum', name: 'Scrum', checked: false },
  { id: 'kanban', name: 'Kanban', checked: false },
  { id: 'lean-startup', name: 'Lean Startup', checked: false },
  { id: 'six-sigma', name: 'Six Sigma', checked: false },
  { id: 'kaizen', name: 'Kaizen', checked: false },
  { id: 'continuous-improvement', name: 'Continuous Improvement', checked: false },
  { id: 'quality-management', name: 'Quality Management', checked: false },
  { id: 'quality-assurance', name: 'Quality Assurance', checked: false },
  { id: 'quality-control', name: 'Quality Control', checked: false },
  { id: 'total-quality-management', name: 'Total Quality Management', checked: false },
  { id: 'iso-9001', name: 'ISO 9001', checked: false },
  { id: 'iso-14001', name: 'ISO 14001', checked: false },
  { id: 'iso-27001', name: 'ISO 27001', checked: false },
  { id: 'iso-45001', name: 'ISO 45001', checked: false },
  { id: 'environmental-management', name: 'Environmental Management', checked: false },
  { id: 'sustainability', name: 'Sustainability', checked: false },
  { id: 'corporate-social-responsibility', name: 'Corporate Social Responsibility', checked: false },
  { id: 'esg', name: 'ESG', checked: false },
  { id: 'diversity-inclusion', name: 'Diversity & Inclusion', checked: false },
  { id: 'equity', name: 'Equity', checked: false },
  { id: 'belonging', name: 'Belonging', checked: false },
  { id: 'workplace-culture', name: 'Workplace Culture', checked: false },
  { id: 'employee-engagement', name: 'Employee Engagement', checked: false },
  { id: 'employee-satisfaction', name: 'Employee Satisfaction', checked: false },
  { id: 'employee-retention', name: 'Employee Retention', checked: false },
  { id: 'talent-acquisition', name: 'Talent Acquisition', checked: false },
  { id: 'recruitment', name: 'Recruitment', checked: false },
  { id: 'hiring', name: 'Hiring', checked: false },
  { id: 'interviewing', name: 'Interviewing', checked: false },
  { id: 'background-checks', name: 'Background Checks', checked: false },
  { id: 'reference-checks', name: 'Reference Checks', checked: false },
  { id: 'skills-testing', name: 'Skills Testing', checked: false },
  { id: 'psychometric-testing', name: 'Psychometric Testing', checked: false },
  { id: 'personality-assessment', name: 'Personality Assessment', checked: false },
  { id: 'cultural-fit-assessment', name: 'Cultural Fit Assessment', checked: false },
  { id: 'talent-management', name: 'Talent Management', checked: false },
  { id: 'succession-planning', name: 'Succession Planning', checked: false },
  { id: 'career-development', name: 'Career Development', checked: false },
  { id: 'leadership-development', name: 'Leadership Development', checked: false },
  { id: 'mentoring', name: 'Mentoring', checked: false },
  { id: 'coaching', name: 'Coaching', checked: false },
  { id: 'feedback', name: 'Feedback', checked: false },
  { id: '360-feedback', name: '360 Feedback', checked: false },
  { id: 'peer-review', name: 'Peer Review', checked: false },
  { id: 'self-assessment', name: 'Self Assessment', checked: false },
  { id: 'competency-management', name: 'Competency Management', checked: false },
  { id: 'skill-mapping', name: 'Skill Mapping', checked: false },
  { id: 'skill-gap-analysis', name: 'Skill Gap Analysis', checked: false },
  { id: 'training-needs-analysis', name: 'Training Needs Analysis', checked: false },
  { id: 'learning-paths', name: 'Learning Paths', checked: false },
  { id: 'microlearning', name: 'Microlearning', checked: false },
  { id: 'gamified-learning', name: 'Gamified Learning', checked: false },
  { id: 'social-learning', name: 'Social Learning', checked: false },
  { id: 'collaborative-learning', name: 'Collaborative Learning', checked: false },
  { id: 'peer-learning', name: 'Peer Learning', checked: false },
  { id: 'experiential-learning', name: 'Experiential Learning', checked: false },
  { id: 'simulation-based-learning', name: 'Simulation-based Learning', checked: false },
  { id: 'virtual-reality-training', name: 'Virtual Reality Training', checked: false },
  { id: 'augmented-reality-training', name: 'Augmented Reality Training', checked: false },
  { id: 'mixed-reality-training', name: 'Mixed Reality Training', checked: false },
  { id: 'immersive-learning', name: 'Immersive Learning', checked: false },
  { id: 'adaptive-learning', name: 'Adaptive Learning', checked: false },
  { id: 'personalized-learning', name: 'Personalized Learning', checked: false },
  { id: 'ai-powered-learning', name: 'AI-powered Learning', checked: false },
  { id: 'intelligent-tutoring', name: 'Intelligent Tutoring', checked: false },
  { id: 'learning-analytics', name: 'Learning Analytics', checked: false },
  { id: 'educational-data-mining', name: 'Educational Data Mining', checked: false },
  { id: 'learning-outcomes', name: 'Learning Outcomes', checked: false },
  { id: 'assessment', name: 'Assessment', checked: false },
  { id: 'evaluation', name: 'Evaluation', checked: false },
  { id: 'certification-management', name: 'Certification Management', checked: false },
  { id: 'compliance-training', name: 'Compliance Training', checked: false },
  { id: 'safety-training', name: 'Safety Training', checked: false },
  { id: 'security-awareness', name: 'Security Awareness', checked: false },
  { id: 'privacy-training', name: 'Privacy Training', checked: false },
  { id: 'ethics-training', name: 'Ethics Training', checked: false },
  { id: 'anti-corruption', name: 'Anti-corruption', checked: false },
  { id: 'anti-money-laundering', name: 'Anti-money Laundering', checked: false },
  { id: 'know-your-customer', name: 'Know Your Customer', checked: false },
  { id: 'customer-due-diligence', name: 'Customer Due Diligence', checked: false },
  { id: 'enhanced-due-diligence', name: 'Enhanced Due Diligence', checked: false },
  { id: 'sanctions-screening', name: 'Sanctions Screening', checked: false },
  { id: 'politically-exposed-persons', name: 'Politically Exposed Persons', checked: false },
  { id: 'transaction-monitoring', name: 'Transaction Monitoring', checked: false },
  { id: 'suspicious-activity-reporting', name: 'Suspicious Activity Reporting', checked: false },
  { id: 'currency-transaction-reporting', name: 'Currency Transaction Reporting', checked: false },
  { id: 'bank-secrecy-act', name: 'Bank Secrecy Act', checked: false },
  { id: 'patriot-act', name: 'Patriot Act', checked: false },
  { id: 'dodd-frank', name: 'Dodd-Frank', checked: false },
  { id: 'mifid', name: 'MiFID', checked: false },
  { id: 'basel-iii', name: 'Basel III', checked: false },
  { id: 'crd-iv', name: 'CRD IV', checked: false },
  { id: 'emir', name: 'EMIR', checked: false },
  { id: 'sftr', name: 'SFTR', checked: false },
  { id: 'priips', name: 'PRIIPs', checked: false },
  { id: 'idd', name: 'IDD', checked: false },
  { id: 'solvency-ii', name: 'Solvency II', checked: false },
  { id: 'ifrs', name: 'IFRS', checked: false },
  { id: 'gaap', name: 'GAAP', checked: false },
  { id: 'coso', name: 'COSO', checked: false },
  { id: 'cobit', name: 'COBIT', checked: false },
  { id: 'itil', name: 'ITIL', checked: false },
  { id: 'prince2', name: 'PRINCE2', checked: false },
  { id: 'pmp', name: 'PMP', checked: false },
  { id: 'agile-certification', name: 'Agile Certification', checked: false },
  { id: 'scrum-master', name: 'Scrum Master', checked: false },
  { id: 'product-owner', name: 'Product Owner', checked: false },
  { id: 'safe', name: 'SAFe', checked: false },
  { id: 'less', name: 'LeSS', checked: false },
  { id: 'nexus', name: 'Nexus', checked: false },
  { id: 'disciplined-agile', name: 'Disciplined Agile', checked: false },
  { id: 'spotify-model', name: 'Spotify Model', checked: false },
  { id: 'holacracy', name: 'Holacracy', checked: false },
  { id: 'sociocracy', name: 'Sociocracy', checked: false },
  { id: 'teal-organization', name: 'Teal Organization', checked: false },
  { id: 'self-management', name: 'Self-management', checked: false },
  { id: 'distributed-leadership', name: 'Distributed Leadership', checked: false },
  { id: 'servant-leadership', name: 'Servant Leadership', checked: false },
  { id: 'transformational-leadership', name: 'Transformational Leadership', checked: false },
  { id: 'authentic-leadership', name: 'Authentic Leadership', checked: false },
  { id: 'ethical-leadership', name: 'Ethical Leadership', checked: false },
  { id: 'inclusive-leadership', name: 'Inclusive Leadership', checked: false },
  { id: 'adaptive-leadership', name: 'Adaptive Leadership', checked: false },
  { id: 'digital-leadership', name: 'Digital Leadership', checked: false },
  { id: 'remote-leadership', name: 'Remote Leadership', checked: false },
  { id: 'virtual-team-management', name: 'Virtual Team Management', checked: false },
  { id: 'cross-cultural-management', name: 'Cross-cultural Management', checked: false },
  { id: 'global-team-management', name: 'Global Team Management', checked: false },
  { id: 'matrix-management', name: 'Matrix Management', checked: false },
  { id: 'stakeholder-management', name: 'Stakeholder Management', checked: false },
  { id: 'relationship-management', name: 'Relationship Management', checked: false },
  { id: 'conflict-resolution', name: 'Conflict Resolution', checked: false },
  { id: 'negotiation', name: 'Negotiation', checked: false },
  { id: 'mediation', name: 'Mediation', checked: false },
  { id: 'arbitration', name: 'Arbitration', checked: false },
  { id: 'dispute-resolution', name: 'Dispute Resolution', checked: false },
  { id: 'grievance-handling', name: 'Grievance Handling', checked: false },
  { id: 'disciplinary-procedures', name: 'Disciplinary Procedures', checked: false },
  { id: 'performance-management', name: 'Performance Management', checked: false },
  { id: 'talent-development', name: 'Talent Development', checked: false },
  { id: 'high-potential-programs', name: 'High Potential Programs', checked: false },
  { id: 'leadership-pipeline', name: 'Leadership Pipeline', checked: false },
  { id: 'executive-coaching', name: 'Executive Coaching', checked: false },
  { id: 'board-governance', name: 'Board Governance', checked: false },
  { id: 'corporate-governance', name: 'Corporate Governance', checked: false },
  { id: 'risk-governance', name: 'Risk Governance', checked: false },
  { id: 'data-governance', name: 'Data Governance', checked: false },
  { id: 'information-governance', name: 'Information Governance', checked: false },
  { id: 'records-management', name: 'Records Management', checked: false },
  { id: 'document-management', name: 'Document Management', checked: false },
  { id: 'content-governance', name: 'Content Governance', checked: false },
  { id: 'digital-asset-management', name: 'Digital Asset Management', checked: false },
  { id: 'brand-asset-management', name: 'Brand Asset Management', checked: false },
  { id: 'creative-asset-management', name: 'Creative Asset Management', checked: false },
  { id: 'media-asset-management', name: 'Media Asset Management', checked: false },
  { id: 'video-management', name: 'Video Management', checked: false },
  { id: 'image-management', name: 'Image Management', checked: false },
  { id: 'audio-management', name: 'Audio Management', checked: false },
  { id: 'podcast-management', name: 'Podcast Management', checked: false },
  { id: 'webinar-management', name: 'Webinar Management', checked: false },
  { id: 'event-management', name: 'Event Management', checked: false },
  { id: 'conference-management', name: 'Conference Management', checked: false },
  { id: 'meeting-management', name: 'Meeting Management', checked: false },
  { id: 'calendar-management', name: 'Calendar Management', checked: false },
  { id: 'scheduling', name: 'Scheduling', checked: false },
  { id: 'resource-booking', name: 'Resource Booking', checked: false },
  { id: 'room-booking', name: 'Room Booking', checked: false },
  { id: 'equipment-booking', name: 'Equipment Booking', checked: false },
  { id: 'vehicle-management', name: 'Vehicle Management', checked: false },
  { id: 'fleet-management', name: 'Fleet Management', checked: false },
  { id: 'maintenance-management', name: 'Maintenance Management', checked: false },
  { id: 'facility-management', name: 'Facility Management', checked: false },
  { id: 'space-management', name: 'Space Management', checked: false },
  { id: 'workplace-management', name: 'Workplace Management', checked: false },
  { id: 'hot-desking', name: 'Hot Desking', checked: false },
  { id: 'desk-booking', name: 'Desk Booking', checked: false },
  { id: 'visitor-management', name: 'Visitor Management', checked: false },
  { id: 'access-control', name: 'Access Control', checked: false },
  { id: 'badge-management', name: 'Badge Management', checked: false },
  { id: 'key-management', name: 'Key Management', checked: false },
  { id: 'security-management', name: 'Security Management', checked: false },
  { id: 'physical-security', name: 'Physical Security', checked: false },
  { id: 'cybersecurity', name: 'Cybersecurity', checked: false },
  { id: 'information-security', name: 'Information Security', checked: false },
  { id: 'network-security', name: 'Network Security', checked: false },
  { id: 'endpoint-security', name: 'Endpoint Security', checked: false },
  { id: 'cloud-security', name: 'Cloud Security', checked: false },
  { id: 'application-security', name: 'Application Security', checked: false },
  { id: 'web-security', name: 'Web Security', checked: false },
  { id: 'mobile-security', name: 'Mobile Security', checked: false },
  { id: 'email-security', name: 'Email Security', checked: false },
  { id: 'identity-management', name: 'Identity Management', checked: false },
  { id: 'privileged-access-management', name: 'Privileged Access Management', checked: false },
  { id: 'single-sign-on', name: 'Single Sign-On', checked: false },
  { id: 'multi-factor-authentication', name: 'Multi-factor Authentication', checked: false },
  { id: 'biometric-authentication', name: 'Biometric Authentication', checked: false },
  { id: 'password-management', name: 'Password Management', checked: false },
  { id: 'encryption', name: 'Encryption', checked: false },
  { id: 'key-management-system', name: 'Key Management System', checked: false },
  { id: 'certificate-management', name: 'Certificate Management', checked: false },
  { id: 'pki', name: 'PKI', checked: false },
  { id: 'digital-signatures', name: 'Digital Signatures', checked: false },
  { id: 'electronic-signatures', name: 'Electronic Signatures', checked: false },
  { id: 'document-signing', name: 'Document Signing', checked: false },
  { id: 'contract-signing', name: 'Contract Signing', checked: false },
  { id: 'approval-workflows', name: 'Approval Workflows', checked: false },
  { id: 'business-process-management', name: 'Business Process Management', checked: false },
  { id: 'workflow-management', name: 'Workflow Management', checked: false },
  { id: 'case-management', name: 'Case Management', checked: false },
  { id: 'ticket-management', name: 'Ticket Management', checked: false },
  { id: 'help-desk', name: 'Help Desk', checked: false },
  { id: 'service-desk', name: 'Service Desk', checked: false },
  { id: 'it-service-management', name: 'IT Service Management', checked: false },
  { id: 'service-catalog', name: 'Service Catalog', checked: false },
  { id: 'service-level-management', name: 'Service Level Management', checked: false },
  { id: 'availability-management', name: 'Availability Management', checked: false },
  { id: 'capacity-management', name: 'Capacity Management', checked: false },
  { id: 'continuity-management', name: 'Continuity Management', checked: false },
  { id: 'supplier-management', name: 'Supplier Management', checked: false },
  { id: 'third-party-risk', name: 'Third-party Risk', checked: false },
  { id: 'vendor-risk-assessment', name: 'Vendor Risk Assessment', checked: false },
  { id: 'due-diligence', name: 'Due Diligence', checked: false },
  { id: 'onboarding-vendors', name: 'Onboarding Vendors', checked: false },
  { id: 'vendor-performance', name: 'Vendor Performance', checked: false },
  { id: 'contract-lifecycle', name: 'Contract Lifecycle', checked: false },
  { id: 'procurement-process', name: 'Procurement Process', checked: false },
  { id: 'sourcing', name: 'Sourcing', checked: false },
  { id: 'rfp-management', name: 'RFP Management', checked: false },
  { id: 'bid-management', name: 'Bid Management', checked: false },
  { id: 'proposal-management', name: 'Proposal Management', checked: false },
  { id: 'tender-management', name: 'Tender Management', checked: false },
  { id: 'quotation-management', name: 'Quotation Management', checked: false },
  { id: 'purchase-order', name: 'Purchase Order', checked: false },
  { id: 'invoice-processing', name: 'Invoice Processing', checked: false },
  { id: 'accounts-payable', name: 'Accounts Payable', checked: false },
  { id: 'accounts-receivable', name: 'Accounts Receivable', checked: false },
  { id: 'credit-management', name: 'Credit Management', checked: false },
  { id: 'collections', name: 'Collections', checked: false },
  { id: 'dunning', name: 'Dunning', checked: false },
  { id: 'payment-processing', name: 'Payment Processing', checked: false },
  { id: 'payment-gateway', name: 'Payment Gateway', checked: false },
  { id: 'payment-orchestration', name: 'Payment Orchestration', checked: false },
  { id: 'payment-routing', name: 'Payment Routing', checked: false },
  { id: 'payment-optimization', name: 'Payment Optimization', checked: false },
  { id: 'payment-analytics', name: 'Payment Analytics', checked: false },
  { id: 'payment-reconciliation', name: 'Payment Reconciliation', checked: false },
  { id: 'settlement', name: 'Settlement', checked: false },
  { id: 'clearing', name: 'Clearing', checked: false },
  { id: 'treasury-management', name: 'Treasury Management', checked: false },
  { id: 'cash-management', name: 'Cash Management', checked: false },
  { id: 'liquidity-management', name: 'Liquidity Management', checked: false },
  { id: 'foreign-exchange', name: 'Foreign Exchange', checked: false },
  { id: 'currency-hedging', name: 'Currency Hedging', checked: false },
  { id: 'interest-rate-management', name: 'Interest Rate Management', checked: false },
  { id: 'derivatives', name: 'Derivatives', checked: false },
  { id: 'trading', name: 'Trading', checked: false },
  { id: 'portfolio-management', name: 'Portfolio Management', checked: false },
  { id: 'investment-management', name: 'Investment Management', checked: false },
  { id: 'wealth-management', name: 'Wealth Management', checked: false },
  { id: 'private-banking', name: 'Private Banking', checked: false },
  { id: 'retail-banking', name: 'Retail Banking', checked: false },
  { id: 'corporate-banking', name: 'Corporate Banking', checked: false },
  { id: 'investment-banking', name: 'Investment Banking', checked: false },
  { id: 'commercial-banking', name: 'Commercial Banking', checked: false },
  { id: 'islamic-banking', name: 'Islamic Banking', checked: false },
  { id: 'digital-banking', name: 'Digital Banking', checked: false },
  { id: 'open-banking', name: 'Open Banking', checked: false },
  { id: 'embedded-finance', name: 'Embedded Finance', checked: false },
  { id: 'banking-as-a-service', name: 'Banking as a Service', checked: false },
  { id: 'payment-as-a-service', name: 'Payment as a Service', checked: false },
  { id: 'lending-as-a-service', name: 'Lending as a Service', checked: false },
  { id: 'insurance-as-a-service', name: 'Insurance as a Service', checked: false },
  { id: 'insurtech', name: 'InsurTech', checked: false },
  { id: 'fintech', name: 'FinTech', checked: false },
  { id: 'regtech', name: 'RegTech', checked: false },
  { id: 'suptech', name: 'SupTech', checked: false },
  { id: 'wealthtech', name: 'WealthTech', checked: false },
  { id: 'proptech', name: 'PropTech', checked: false },
  { id: 'legaltech', name: 'LegalTech', checked: false },
  { id: 'edtech', name: 'EdTech', checked: false },
  { id: 'healthtech', name: 'HealthTech', checked: false },
  { id: 'medtech', name: 'MedTech', checked: false },
  { id: 'biotech', name: 'BioTech', checked: false },
  { id: 'agtech', name: 'AgTech', checked: false },
  { id: 'foodtech', name: 'FoodTech', checked: false },
  { id: 'retailtech', name: 'RetailTech', checked: false },
  { id: 'fashiontech', name: 'FashionTech', checked: false },
  { id: 'beautytech', name: 'BeautyTech', checked: false },
  { id: 'traveltech', name: 'TravelTech', checked: false },
  { id: 'mobility', name: 'Mobility', checked: false },
  { id: 'transportation', name: 'Transportation', checked: false },
  { id: 'logistics-tech', name: 'Logistics Tech', checked: false },
  { id: 'supply-chain-tech', name: 'Supply Chain Tech', checked: false },
  { id: 'manufacturing-tech', name: 'Manufacturing Tech', checked: false },
  { id: 'industry-4-0', name: 'Industry 4.0', checked: false },
  { id: 'smart-manufacturing', name: 'Smart Manufacturing', checked: false },
  { id: 'digital-twin', name: 'Digital Twin', checked: false },
  { id: 'predictive-maintenance', name: 'Predictive Maintenance', checked: false },
  { id: 'condition-monitoring', name: 'Condition Monitoring', checked: false },
  { id: 'asset-performance', name: 'Asset Performance', checked: false },
  { id: 'operational-excellence', name: 'Operational Excellence', checked: false },
  { id: 'lean-manufacturing', name: 'Lean Manufacturing', checked: false },
  { id: 'just-in-time', name: 'Just-in-Time', checked: false },
  { id: 'total-productive-maintenance', name: 'Total Productive Maintenance', checked: false },
  { id: 'overall-equipment-effectiveness', name: 'Overall Equipment Effectiveness', checked: false },
  { id: 'statistical-process-control', name: 'Statistical Process Control', checked: false },
  { id: 'design-for-six-sigma', name: 'Design for Six Sigma', checked: false },
  { id: 'design-for-manufacturing', name: 'Design for Manufacturing', checked: false },
  { id: 'design-for-assembly', name: 'Design for Assembly', checked: false },
  { id: 'design-for-sustainability', name: 'Design for Sustainability', checked: false },
  { id: 'circular-economy', name: 'Circular Economy', checked: false },
  { id: 'waste-management', name: 'Waste Management', checked: false },
  { id: 'recycling', name: 'Recycling', checked: false },
  { id: 'upcycling', name: 'Upcycling', checked: false },
  { id: 'renewable-energy', name: 'Renewable Energy', checked: false },
  { id: 'clean-energy', name: 'Clean Energy', checked: false },
  { id: 'energy-management', name: 'Energy Management', checked: false },
  { id: 'carbon-management', name: 'Carbon Management', checked: false },
  { id: 'carbon-footprint', name: 'Carbon Footprint', checked: false },
  { id: 'carbon-offset', name: 'Carbon Offset', checked: false },
  { id: 'carbon-neutral', name: 'Carbon Neutral', checked: false },
  { id: 'net-zero', name: 'Net Zero', checked: false },
  { id: 'climate-change', name: 'Climate Change', checked: false },
  { id: 'climate-risk', name: 'Climate Risk', checked: false },
  { id: 'climate-adaptation', name: 'Climate Adaptation', checked: false },
  { id: 'climate-mitigation', name: 'Climate Mitigation', checked: false },
  { id: 'green-finance', name: 'Green Finance', checked: false },
  { id: 'sustainable-finance', name: 'Sustainable Finance', checked: false },
  { id: 'impact-investing', name: 'Impact Investing', checked: false },
  { id: 'esg-investing', name: 'ESG Investing', checked: false },
  { id: 'socially-responsible-investing', name: 'Socially Responsible Investing', checked: false },
  { id: 'ethical-investing', name: 'Ethical Investing', checked: false },
  { id: 'sustainable-development-goals', name: 'Sustainable Development Goals', checked: false },
  { id: 'united-nations-global-compact', name: 'United Nations Global Compact', checked: false },
  { id: 'global-reporting-initiative', name: 'Global Reporting Initiative', checked: false },
  { id: 'sustainability-accounting', name: 'Sustainability Accounting', checked: false },
  { id: 'integrated-reporting', name: 'Integrated Reporting', checked: false },
  { id: 'triple-bottom-line', name: 'Triple Bottom Line', checked: false },
  { id: 'stakeholder-capitalism', name: 'Stakeholder Capitalism', checked: false },
  { id: 'purpose-driven-business', name: 'Purpose-driven Business', checked: false },
  { id: 'b-corporation', name: 'B Corporation', checked: false },
  { id: 'benefit-corporation', name: 'Benefit Corporation', checked: false },
  { id: 'social-enterprise', name: 'Social Enterprise', checked: false },
  { id: 'social-entrepreneurship', name: 'Social Entrepreneurship', checked: false },
  { id: 'impact-measurement', name: 'Impact Measurement', checked: false },
  { id: 'theory-of-change', name: 'Theory of Change', checked: false },
  { id: 'logic-model', name: 'Logic Model', checked: false },
  { id: 'results-framework', name: 'Results Framework', checked: false },
  { id: 'monitoring-evaluation', name: 'Monitoring & Evaluation', checked: false },
  { id: 'program-evaluation', name: 'Program Evaluation', checked: false },
  { id: 'impact-evaluation', name: 'Impact Evaluation', checked: false },
  { id: 'randomized-controlled-trial', name: 'Randomized Controlled Trial', checked: false },
  { id: 'quasi-experimental-design', name: 'Quasi-experimental Design', checked: false },
  { id: 'difference-in-differences', name: 'Difference-in-Differences', checked: false },
  { id: 'propensity-score-matching', name: 'Propensity Score Matching', checked: false },
  { id: 'instrumental-variables', name: 'Instrumental Variables', checked: false },
  { id: 'regression-discontinuity', name: 'Regression Discontinuity', checked: false },
  { id: 'natural-experiment', name: 'Natural Experiment', checked: false },
  { id: 'field-experiment', name: 'Field Experiment', checked: false },
  { id: 'lab-experiment', name: 'Lab Experiment', checked: false },
  { id: 'behavioral-economics', name: 'Behavioral Economics', checked: false },
  { id: 'nudge', name: 'Nudge', checked: false },
  { id: 'choice-architecture', name: 'Choice Architecture', checked: false },
  { id: 'behavioral-insights', name: 'Behavioral Insights', checked: false },
  { id: 'behavioral-design', name: 'Behavioral Design', checked: false },
  { id: 'persuasive-design', name: 'Persuasive Design', checked: false },
  { id: 'gamification-design', name: 'Gamification Design', checked: false },
  { id: 'user-centered-design', name: 'User-centered Design', checked: false },
  { id: 'human-centered-design', name: 'Human-centered Design', checked: false },
  { id: 'service-design', name: 'Service Design', checked: false },
  { id: 'experience-design', name: 'Experience Design', checked: false },
  { id: 'customer-experience', name: 'Customer Experience', checked: false },
  { id: 'user-experience-design', name: 'User Experience Design', checked: false },
  { id: 'user-interface-design', name: 'User Interface Design', checked: false },
  { id: 'interaction-design', name: 'Interaction Design', checked: false },
  { id: 'visual-design', name: 'Visual Design', checked: false },
  { id: 'graphic-design', name: 'Graphic Design', checked: false },
  { id: 'web-design', name: 'Web Design', checked: false },
  { id: 'mobile-design', name: 'Mobile Design', checked: false },
  { id: 'responsive-design', name: 'Responsive Design', checked: false },
  { id: 'adaptive-design', name: 'Adaptive Design', checked: false },
  { id: 'progressive-web-app', name: 'Progressive Web App', checked: false },
  { id: 'single-page-application', name: 'Single Page Application', checked: false },
  { id: 'server-side-rendering', name: 'Server-side Rendering', checked: false },
  { id: 'static-site-generation', name: 'Static Site Generation', checked: false },
  { id: 'jamstack', name: 'JAMstack', checked: false },
  { id: 'headless-cms', name: 'Headless CMS', checked: false },
  { id: 'api-first', name: 'API-first', checked: false },
  { id: 'microservices-architecture', name: 'Microservices Architecture', checked: false },
  { id: 'event-driven-architecture', name: 'Event-driven Architecture', checked: false },
  { id: 'domain-driven-design', name: 'Domain-driven Design', checked: false },
  { id: 'clean-architecture', name: 'Clean Architecture', checked: false },
  { id: 'hexagonal-architecture', name: 'Hexagonal Architecture', checked: false },
  { id: 'onion-architecture', name: 'Onion Architecture', checked: false },
  { id: 'layered-architecture', name: 'Layered Architecture', checked: false },
  { id: 'mvc-architecture', name: 'MVC Architecture', checked: false },
  { id: 'mvp-architecture', name: 'MVP Architecture', checked: false },
  { id: 'mvvm-architecture', name: 'MVVM Architecture', checked: false },
  { id: 'flux-architecture', name: 'Flux Architecture', checked: false },
  { id: 'redux-pattern', name: 'Redux Pattern', checked: false },
  { id: 'observer-pattern', name: 'Observer Pattern', checked: false },
  { id: 'publisher-subscriber', name: 'Publisher-Subscriber', checked: false },
  { id: 'command-pattern', name: 'Command Pattern', checked: false },
  { id: 'strategy-pattern', name: 'Strategy Pattern', checked: false },
  { id: 'factory-pattern', name: 'Factory Pattern', checked: false },
  { id: 'singleton-pattern', name: 'Singleton Pattern', checked: false },
  { id: 'adapter-pattern', name: 'Adapter Pattern', checked: false },
  { id: 'decorator-pattern', name: 'Decorator Pattern', checked: false },
  { id: 'facade-pattern', name: 'Facade Pattern', checked: false },
  { id: 'proxy-pattern', name: 'Proxy Pattern', checked: false },
  { id: 'builder-pattern', name: 'Builder Pattern', checked: false },
  { id: 'prototype-pattern', name: 'Prototype Pattern', checked: false },
  { id: 'chain-of-responsibility', name: 'Chain of Responsibility', checked: false },
  { id: 'iterator-pattern', name: 'Iterator Pattern', checked: false },
  { id: 'mediator-pattern', name: 'Mediator Pattern', checked: false },
  { id: 'memento-pattern', name: 'Memento Pattern', checked: false },
  { id: 'state-pattern', name: 'State Pattern', checked: false },
  { id: 'template-method', name: 'Template Method', checked: false },
  { id: 'visitor-pattern', name: 'Visitor Pattern', checked: false },
  { id: 'solid-principles', name: 'SOLID Principles', checked: false },
  { id: 'dry-principle', name: 'DRY Principle', checked: false },
  { id: 'kiss-principle', name: 'KISS Principle', checked: false },
  { id: 'yagni-principle', name: 'YAGNI Principle', checked: false },
  { id: 'separation-of-concerns', name: 'Separation of Concerns', checked: false },
  { id: 'single-responsibility', name: 'Single Responsibility', checked: false },
  { id: 'open-closed-principle', name: 'Open-Closed Principle', checked: false },
  { id: 'liskov-substitution', name: 'Liskov Substitution', checked: false },
  { id: 'interface-segregation', name: 'Interface Segregation', checked: false },
  { id: 'dependency-inversion', name: 'Dependency Inversion', checked: false },
  { id: 'inversion-of-control', name: 'Inversion of Control', checked: false },
  { id: 'dependency-injection', name: 'Dependency Injection', checked: false },
  { id: 'aspect-oriented-programming', name: 'Aspect-oriented Programming', checked: false },
  { id: 'functional-programming', name: 'Functional Programming', checked: false },
  { id: 'object-oriented-programming', name: 'Object-oriented Programming', checked: false },
  { id: 'procedural-programming', name: 'Procedural Programming', checked: false },
  { id: 'declarative-programming', name: 'Declarative Programming', checked: false },
  { id: 'imperative-programming', name: 'Imperative Programming', checked: false },
  { id: 'reactive-programming', name: 'Reactive Programming', checked: false },
  { id: 'event-sourcing', name: 'Event Sourcing', checked: false },
  { id: 'cqrs', name: 'CQRS', checked: false },
  { id: 'saga-pattern', name: 'Saga Pattern', checked: false },
  { id: 'circuit-breaker', name: 'Circuit Breaker', checked: false },
  { id: 'bulkhead-pattern', name: 'Bulkhead Pattern', checked: false },
  { id: 'timeout-pattern', name: 'Timeout Pattern', checked: false },
  { id: 'retry-pattern', name: 'Retry Pattern', checked: false },
  { id: 'rate-limiting-pattern', name: 'Rate Limiting Pattern', checked: false },
  { id: 'throttling', name: 'Throttling', checked: false },
  { id: 'debouncing', name: 'Debouncing', checked: false },
  { id: 'caching-strategies', name: 'Caching Strategies', checked: false },
  { id: 'cache-aside', name: 'Cache-aside', checked: false },
  { id: 'write-through', name: 'Write-through', checked: false },
  { id: 'write-behind', name: 'Write-behind', checked: false },
  { id: 'refresh-ahead', name: 'Refresh-ahead', checked: false },
  { id: 'distributed-caching', name: 'Distributed Caching', checked: false },
  { id: 'in-memory-caching', name: 'In-memory Caching', checked: false },
  { id: 'redis-caching', name: 'Redis Caching', checked: false },
  { id: 'memcached', name: 'Memcached', checked: false },
  { id: 'database-optimization', name: 'Database Optimization', checked: false },
  { id: 'query-optimization', name: 'Query Optimization', checked: false },
  { id: 'index-optimization', name: 'Index Optimization', checked: false },
  { id: 'database-sharding', name: 'Database Sharding', checked: false },
  { id: 'database-replication', name: 'Database Replication', checked: false },
  { id: 'database-partitioning', name: 'Database Partitioning', checked: false },
  { id: 'database-clustering', name: 'Database Clustering', checked: false },
  { id: 'database-migration', name: 'Database Migration', checked: false },
  { id: 'schema-evolution', name: 'Schema Evolution', checked: false },
  { id: 'data-modeling', name: 'Data Modeling', checked: false },
  { id: 'entity-relationship-modeling', name: 'Entity Relationship Modeling', checked: false }
];
